// Main modules
import { Injectable } from '@angular/core';

@Injectable()
export class MultiLanguageService {
    // This will be loaded from server when the language is selected
    public text = {
        general: {
            charsLeft: 'karater kaldi',
            selectPicture: 'Resim sec',
            deletePicture: 'Resim sil',
            upload: 'Yukle',
            turn: 'Cevir',
            cancel: 'Iptal',
            pictureSuccessful: 'Resim basariyla yuklendi!',
            share: 'Paylas',
            close: 'Kapat',
            edit: 'Duzenle',
            delete: 'Sil',
            areYouSure: 'Emin misiniz?',
            approve: 'Onayla',
            messageTitle: 'Mesaj',
            refresh: 'Yenile',
            sendMessage: 'Mesaj Gonder',
            anonymChat: 'Anonim Gorusme',
            areSureDeletePicture: 'Bu resmi silmek istediginizden emin misiniz?'
        },
        post: {
            shareHere: 'Kutatku\'da paylas',
            sharedDate: 'tarihinde paylasildi',
            seeAllWhoShared: 'Tum paylasanlari gor',
            placeHolderComment: 'Yorumunuz',
            openLink: 'Linke git',
            noCommentsYet: 'Henuz bu paylasim ile ilgili hic bir yorum yapilmamis.',
            deleteShare: 'Paylasimi sil',
            whoShared: 'En son paylasan',
            top10: 'En cok konusulanlar',
            allPosts: 'Butun paylasimlar',
            privatePosts: 'Ozel paylasimlar'
        },
        admin: {
            help: 'Yardim',
            fillOutForm: 'Bu formu doldurarak sitemiz ile ilgili oneri ve sikayetlerinizi bize iletebilirsiniz.',
            subject: 'Konu',
            suggestion: 'Oneri',
            request: 'Istek',
            complaint: 'Sikayet',
            bug: 'Ariza',
            send: 'Gonder',
            placeHolder: 'Mesajinizi buraya yazin',
            adText: 'Ilan yazisi',
            adTitle: 'Ilan basligi'
        },
        messaging: {
            privateChatWith: 'ile ozel konusma',
            creditWarning: 'Yabanci birine mesaj atmak 10 kredidir. Kalan kredi',
            answer: 'Cevapla'
        },
        complaint: {
            title: 'Sikayet',
            message: 'Mesaj',
            owner: 'Sahibi',
            date: 'Paylasilma tarihi',
            complanier: 'Sikayet eden',
            process: 'Islem',
            processText: 'Sikayet edilen kisiyi dilediginiz gun sayisi kadar sohbetlerden uzaklastirabilirsiniz.',
            ban: 'Yasakla',
            placeHolderDays: 'Gun sayisi'
        },
        credit: {
            title: 'Kredi Islemleri',
            who: 'Kredi istenen yada gonderilecek kisi',
            avaiable: 'Mevcut kredi bakiyeniz',
            amount: 'Gonderilecek ya da istenecek kredi miktarini giriniz',
            placeHolderAmount: 'Kredi miktarini buraya giriniz',
            send: 'Gonder',
            ask: 'Iste',
            limit: 'Limit asildi',
            sendSentenceIntro: '<b><big>',
            sendSentenceMiddle: '</big></b> kredi gondermek istiyorsunuz. <br>Gonderdikten sonra <b><big>',
            sendSentenceEnd: '</big></b> krediniz kalacaktir. <br> Bu islemi gerceklestirmek istediginize emin misiniz?',
            sendSuccessSentenceIntro: 'Kredi hediyeniz basari ile gonderilmistir! <br> Kalan kredi: <b><big>',
            sendSuccessSentenceEnd: '</big></b>',
            askSentenceIntro: ' isimli kullanicidan <b><big>',
            askSentenceMiddle: '</big></b> kredi istiyorsunuz. <br> Isteginiz kabul edildikten sonra <b><big>',
            askSentenceEnd: '</big></b> krediniz olacaktir. <br> Bu islemi gerceklestirmek istediginize emin misiniz?',
            askSuccessSentenceIntro: ' isimli kullaniciya <b><big>',
            askSuccessSentenceEnd: '</big></b> kredi isteginiz basari ile gonderilmistir!'

        },
        classifieds: {
            title: 'Seri Ilanlar',
            vehicle: 'Tasit',
            service: 'Servis',
            jobs: 'Is',
            realEstate: 'Emlak',
            buySell: 'Alim/Satim',
            noClassifieds: 'Hic bir ilan bulunamadi',
            shareHere: 'Kutatku seri ilanlarda paylas',
            category: 'Kategori',
            date: 'Yayinlanma',
        },
        auth: {
            login: 'Giris yap',
            signup: 'Kayit ol',
            forgotPassword: 'Sifremi unuttum',
            forgotPasswordMessage: 'Sifrenizi mi unuttunuz? Sorun degil. Asagidaki adimlari takip edin, ve sifrenizi yenileyin!',
            enterEmail: 'E-mail adresinizi giriniz.',
            sendCode: 'Kodu gonder',
            enterCode: 'E-mail adresinize gonderdigimiz kodu giriniz.',
            enterNewPassword: 'Yeni sifreyi giriniz',
            changePassword: 'Sifreyi degistir',
            passwordRules: 'Sifreniz asagidaki kurallara uygun olmalidir:',
            passwordRule1: 'En az 8 karakter',
            passwordRule2: 'En az 1 kucuk harf',
            passwordRule3: 'En az 1 buyuk harf',
            passwordRule4: 'En az 1 sayi',
            passwordRule5: 'En az 1 ozel karakter (!@#$%^&*) icermelidir',
            placeHolderEmail: 'E-posta',
            placeHolderPassword: 'Sifre',
            placeHolderNewPassword: 'Yeni sifre',
            placeHolderNickname: 'Takma isim',
            placeHolderCode: 'Kod',
            placeHolderChatNickname: 'Rumuz (anonim sohbet)',
            placeHolderName: 'Isim',
            placeHolderLastname: 'Soy isim',
            areYouSureLogout: 'Cikis yapmak istediginizden emin misiniz?',
            placeHolderPasswordAgain: 'Sifreyi tekrar giriniz',
            placeHolderShortMessage: 'Kisa bir mesaj yaziniz (max. 128 karakter)',
            shortMessageMessage: 'Son olarak, nereden katildiginizi ve kim oldugunuzu anlatan kisa bir mesaj ile Kutatku\'ya merhaba deyin! Dilerseniz, daha sonra bu mesaji dilediginiz gibi degistirebilirsiniz. <i>(Max 256 karakter)</i>',
            whyNameLastnameMessage: 'Isim ve soyismi doldurmak, arkadas aramalarinda kolay bulunabilmeniz icin tavsiye olunur. Kalan bilgileri hesabinizi actiktan sonra doldurabilirsiniz.'
        },
        navigation: {
            homepage: 'Ana sayfa',
            classifieds: 'Ilanlar',
            help: 'Yardim',
            profile: 'Hesap',
            gotoprofile: 'Hesaba git',
            logout: 'Cikis yap'
        },
        search: {
            resultsFound: 'sonuc bulundu',
            search: 'Arkadas ara'
        },
        inbox: {
            privateMessages: 'Ozel Mesajlar',
            notifications: 'Bildirimler',
            requests: 'Istekler',
            chat: 'Canli Sohbet',
            sentRequest: 'Takip istegi yolladi',
            noRequestFound: 'Hic bir istek bulunamadi',
            noMessageFound: 'Hic bir mesaj bulunamadi',
            noNotificationFound: 'Hic bir bildirim bulunamadi',
            selectRoom: 'Oda seciniz',
            inviteToPrivate: 'Ozel sohbete cagir',
            showMore: 'Daha yukle',
            complain: 'Sikayet et',
            selectColor: 'Renk secin',
            black: 'siyah',
            red: 'kirmizi',
            purple: 'mor',
            yellow: 'sari',
            green1: 'yesil 1',
            green2: 'yesil 2',
            gray: 'gri',
            lightGray: 'acik gri',
            darkBlue: 'lacivert',
            blue: 'mavi',
            orange: 'turuncu',
            complaintReason: 'Sebep (max. 100 karakter)'
        },
        user: {
            areYouSureCloseAccount: 'Bu hesabi tamamen kapatmak istediginizden emin misiniz?',
            profileUpdated: 'Profiliniz basari ile guncellenmistir',
            accountClosed: 'Hesap basariyla kapanmistir ve alakali her sey silinmistir. Gule gule!',
            passwordReset: 'Sifreniz basari ile degismistir!',
            sharePrivate: 'Ozel Kutatku duvarinda paylas',
            addCoverPicture: 'Kapak resmi ekle',
            deleteCoverPicture: 'Kapak resmi sil',
            newPeople: 'Yeni arkadaslar kesfedin',
            nameLastname: 'Isim, soyisim',
            birthday: 'Dogum gunu',
            jobStatus: 'Is durumu',
            educationStatus: 'Egitim durumu',
            bio: 'Oz gecmis',
            socialMedia: 'Sosyal medya',
            follow: 'Takip et',
            accept: 'Kabul',
            leave: 'Ayril',
            askCredit: 'Kredi',
            talk: 'Konus',
            noPosts: 'Hic bir paylasim bulunamadi!',
            noInfo: 'Bu kullanici hakkinda henuz pek bir bilgi yok.',
            info: 'Bilgiler',
            email: 'E-mail',
            nickName: 'Takma isim',
            chatNickname: 'Rumuz (anonim sohbet)',
            shortMessage: 'Kisa mesaj (aramalar icin)',
            name: 'Isim',
            lastName: 'Soyisim',
            friends: 'Arkadaslar',
            noFriends: 'Hic bir arkadas bulunamadi',
            myWall: 'Duvarim',
            accountSettings: 'Hesap ayarlari',
            newPassword: 'Sifre yenile',
            closeAccount: 'Hesabi kapat',
            placeHolderOldPassword: 'Eski sifre',
            placeHolderNewPassword: 'Yeni sifre',
            placeHolderEnterPassword: 'Sifrenizi giriniz'
        },
        chat: {
            acceptRoomRules: 'Bu odaya girmeden once asagidaki kurallari kabul etmelisiniz:',
            youAreBanned: 'Sohbetten kovuldunuz!',
            complaintSent: 'Sikayet gonderildi'
        },
        errors: {
            title: 'Sorun',
            closingAccount: 'Hesabi kapatirken bir sorun olustu',
            passwordReset: 'Sifrenizi degistirirken bir sorun olustu',
            subjects: 'Konulari gosterirken bir sorun olustu',
            friendList: 'Arkadas listesini yuklerken bir sorun olustu',
            findingUsers: 'Kullanicilar bulunurken bir sorun olustu',
            showingPost: 'Paylasimi gosterirken bir sorun olustu',
            deletingNotification: 'Bildirim silinirken bir sorun olustu',
            checkingFriendship: 'Arkadaslik kontrolunde bir sorun olustu!',
            sendErrorMessage: 'Hata raporu gonder',
            inbox: 'Mesajlar ve istekler goruntulenirken bir sorun olustu',
            user: 'Profil yuklenirken bir sorun olustu',
            post: 'Gonderi yuklenirken bir sorun olustu',
            sendingMessage: 'Mesajinizi gonderirken bir hata olustu',
            showingAds: 'Ilanlari goruntulerken bir sorun olustu',
            showingPosts: 'Paylasimlari goruntulerken bir sorun olustu',
            login: 'Giris yapilamadi, lutfen bilgilerinizi kontrol ediniz',
            wrongCode: 'Yanlis kod girdiniz, lutfen tekrar deneyiniz',
            unexplanied: 'Bilinmeyen bir sorun olustu',
            signup: 'Kayit olurken bir problem olustu',
            passwords: 'Iki sifrenin ayni oldugundan emin olun!',
            sharingAd: 'Ilani paylasirken bir sorun olustu',
            fillOutAll: 'Lutfen butun bilgileri doldurunuz',
            pictureUpload: 'Resim yuklenirken bir sorun olustu',
            picturesUpload: 'Resimler yuklenirken bir sorun olustu',
            pictureSize: 'Resimler 1 MB\'den buyuk olmamalidir. 1 MB\'den buyuk resimler yuklenmedi.',
            pictureLimit: 'Maksimum 6 resim hakkini doldurdunuz. Bazi resimleri silerek yeni resimlere yer acabilirsiniz.',
            pictureDelete: 'Resim silinirken bir sorun olustu',
            pictureRatio: 'Resim cok uzun! Yukselik ve genislik orani 3/1\'i gecemez.',
            deletingAd: 'Ilan silinirken bir sorun olustu',
            banning: 'Kullanici yasaklanirken bir sorun olustu.',
            creditRequestSending: 'Kredi isteginiz gonderilirken bir sorun olustu!',
            creditGiftSending: 'Kredi hediyesi gonderilirken bir sorun olustu!',
            reportSent: 'Hata raporu gonderilemedi!',
            updatingPost: 'Gonderi guncellenirken bir sorun olustu!',
            sharingPost: 'Gonderi paylasilirken bir sorun olustu!',
            deletingPost: 'Gonderi silinirken bir sorun olustu!',
            answerPost: 'Paylasima cevap verilirken bir sorun olustu',
            deletingAnswer: 'Cevap silinirken bir sorun olustu',
            link: 'Linkte bir sorun olustu',
            liking: 'Paylasim begenilirken bir sorun olustu!',
            followRequestSent: 'Takip istegi yollarken bir sorun olustu!',
            requestAccepted: 'Takip istegi kabul edilirken bir sorun olustu!',
            requestCancelled: 'Takip istegi iptal edilirken bir sorun olustu!',
            unfriend: 'Arkadasliktan cikarilirken bir sorun olustu!',
            sendComplaint: 'Sikayet gonderilirken bir sorun olustu',
            enteringChatRoom: 'Odaya girilirken bir sorun olustu',
            profileUpdated: 'Profiliniz guncellenirken bir sorun olustu'
        },
        success: {
            messageSent: 'Mesajiniz basariyla gonderildi!',
            welcome: 'Hosgeldin',
            sentCodeToEmail: 'Girdiginiz adrese bir sifre yolladik, lutfen kontrol ediniz',
            passwordReset: 'Sifreniz basari ile yenilenmistir! Lutfen tekrar giris yapiniz',
            signup: 'Kayit oldugunuz icin tesekkurler! Artik siteye giris yapabilirsiniz.',
            banned: 'Kullanici basari ile yasaklandi.',
            reportSent: 'Hata raporu basariyla gonderildi',
            followRequestSent: 'Takip istegi basari ile yollandi!',
            requestAccepted: 'Takip istegi kabul edildi!',
            requestCancelled: 'Takip istegi iptal edildi',
            unfriended: 'Arkadasliktan cikarildi!'
        },
        question: {
            deleteMessage: 'Bu mesaji silmek istediginizden emin misiniz?',
            cancelRequest: 'Bu istegi geri cevirmek istediginizden emin misiniz?',
            unfriend: 'Bu kisiyi arkadasliktan cikarmak istediginize emin misiniz?'
        }
    }
}
